# Generated by Django 4.1.6 on 2023-02-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(choices=[('noun', 'noun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb')], max_length=100)),
                ('definition', models.CharField(max_length=250)),
                ('etymology', models.CharField(max_length=250)),
                ('connotation', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], max_length=100)),
                ('sentence', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.word')),
            ],
        ),
        migrations.CreateModel(
            name='NearbyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearby_word', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.word')),
            ],
        ),
    ]
