# Generated by Django 4.1.6 on 2023-02-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='etymology',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('nou', 'Noun'), ('ver', 'Verb'), ('adj', 'Adjective'), ('adv', 'Adverb')], default='-- select one --', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(max_length=250),
        ),
    ]
