# Generated by Django 4.1.6 on 2023-02-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mood_word_mood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mood',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='mood',
            new_name='label',
        ),
    ]
