# Generated by Django 4.1.6 on 2023-02-09 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_word_etymology_word_part_of_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='etymology',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('nou', 'noun'), ('ver', 'verb'), ('adj', 'adjective'), ('adv', 'adverb')], max_length=3),
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.word')),
            ],
        ),
    ]
