# Generated by Django 4.1.6 on 2023-02-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_mood_label_rename_mood_word_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='label',
        ),
        migrations.AddField(
            model_name='label',
            name='memo',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='labels',
            field=models.ManyToManyField(to='main_app.label'),
        ),
        migrations.AlterField(
            model_name='word',
            name='connotation',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='word',
            name='sentence',
            field=models.TextField(max_length=300),
        ),
    ]
