# Generated by Django 4.1.6 on 2023-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_word_label_label_memo_label_name_word_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink')], default='green', max_length=100),
            preserve_default=False,
        ),
    ]
