# Generated by Django 4.1.6 on 2023-02-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_word_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'noun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb')], max_length=100),
        ),
    ]
