# Generated by Django 4.1.6 on 2023-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_word_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='connotation',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='neutral', max_length=100),
            preserve_default=False,
        ),
    ]
