# Generated by Django 4.1.6 on 2023-02-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_word_connotation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Synonym',
            new_name='Nearby',
        ),
        migrations.RenameField(
            model_name='nearby',
            old_name='synonym',
            new_name='nearby',
        ),
    ]
