# Generated by Django 4.1.6 on 2023-02-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_synonym_nearby_rename_synonym_nearby_nearby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nearby',
            new_name='NearbyWord',
        ),
        migrations.RenameField(
            model_name='nearbyword',
            old_name='nearby',
            new_name='nearby_word',
        ),
    ]
